### ISSUE TITLE
Ender Man has no hatred against players and does not attack players

### ISSUE THREAD

**Issue by Xueyo02** [BentoBoxWorld/BSkyBlock#346] opened 2020-06-27 06:01 UTC
Ender Man has no hatred against players and does not attack players
version:1.16.1
bentobox version:1.13.1
BskyBlock version:1.13.1
Core Version: Spigot 1.16.1

**Comment by Poslovitch** [comment] 2020-06-27 09:05
Could you please make sure it still occurs if BentoBox is not on the server? I highly doubt that it is caused by BentoBox.

**Comment by tastybento** [comment] 2020-06-27 15:24
I can replicate this issue on spigot with no BentoBox installed. Seems like a vanilla bug right now.

**Comment by tastybento** [comment] 2020-06-27 15:26
He just gets angry but never moves to attack. This is on the nether island with BentoBox removed.
<img width="863" alt="Screen Shot 2020-06-27 at 8 22 54 AM" src="https://user-images.githubusercontent.com/4407265/85925803-cb3e3400-b84f-11ea-92ce-d2206a9b74c6.png">

**Comment by tastybento** [comment] 2020-06-28 03:59
This is fixed in the latest version of spigot. Download it and it should work.

**Closed by tastybento** 2020-06-28 03:59 UTC
Labels: 1.16
