### ISSUE TITLE
Hi! Please help me. I really need to have only two ranks on the islands: visitor and member. Or at least I need players without "op" to see only these two ranks. I have seen several requests on this topic, but I have not found anything. How can I make only two ranks?

### ISSUE THREAD

**Issue by Pikachu2p** [BentoBoxWorld/BSkyBlock#444] opened 2021-09-24 21:16 UTC

**Comment by BONNe** [comment] 2021-09-24 21:53
Simple answer: you cannot.

Banned, coop, trusted has main functionallity within plugin. 
The only underutilized rank is sub-owner.

There are feature requests that wants a customization in this part, but due to complexity and time constraints, it is not done.

**Comment by tastybento** [comment] 2021-09-24 22:57
Duplicate of https://github.com/BentoBoxWorld/BentoBox/issues/528

**Closed by tastybento** 2021-09-24 22:57 UTC

**Comment by Pikachu2p** [comment] 2021-09-26 15:46
Ok. Thanks for answer
