### ISSUE TITLE
Plugin is unresponsive after creating large schem island.

### ISSUE THREAD

**Issue by Stefatorus** [BentoBoxWorld/BSkyBlock#44] opened 2019-01-10 14:39 UTC
**Description**
A stacktrace shows up when pasting a really large island. The server becomes unresponsive even though the block ticklimit is the default and the server is running on an i7-4790k processor.

**Steps to reproduce the behavior:**
1. Supposedly happens with really large island schems. This is the stack trace I get.
`[09:29:46] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-488 (MC: 1.13.2) ---
[09:29:46] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[09:29:46] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:29:46] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[09:29:46] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:29:46] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[09:29:46] [Paper Watchdog Thread/ERROR]: 	PID: 26 | Suspended: false | Native: false | State: RUNNABLE
[09:29:46] [Paper Watchdog Thread/ERROR]: 	Stack:
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.IBlockData.isAir(IBlockData.java:77)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkSection.setType(ChunkSection.java:62)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.generator.CraftChunkData.setBlock(CraftChunkData.java:144)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.generator.CraftChunkData.setBlock(CraftChunkData.java:52)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.generator.CraftChunkData.setBlock(CraftChunkData.java:42)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bskyblock.generators.ChunkGeneratorWorld.generateChunkData(ChunkGeneratorWorld.java:47)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.generator.CustomChunkGenerator.createChunk(CustomChunkGenerator.java:71)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkTaskBase.a(SourceFile:13)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:109)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:16)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2546/1185882004.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2544/1980097744.accept(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2544/1980097744.accept(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2544/1980097744.accept(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2544/1980097744.accept(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2544/1980097744.accept(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2544/1980097744.accept(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$2543/808048947.apply(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.Map.computeIfAbsent(Map.java:957)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler$$Lambda$2534/1115708350.get(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.SchedulerBatch.a(SchedulerBatch.java:38)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.ChunkProviderServer.generateChunk(ChunkProviderServer.java:205)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftWorld.regenerateChunk(CraftWorld.java:268)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.util.DeleteIslandChunks.<init>(DeleteIslandChunks.java:41)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.IslandsManager.deleteIsland(IslandsManager.java:252)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.NewIsland.lambda$newIsland$0(NewIsland.java:173)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		world.bentobox.bentobox.managers.island.NewIsland$$Lambda$3773/1964003918.run(Unknown Source)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[09:29:46] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[09:29:46] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:29:46] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---`

**Expected behavior**
Island pastes slower but doesn't end up to these messages showing up or the plugin becoming unresponsive.

**Screenshots**
- Not applicable

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): YAML
 - OS: [e.g. iOS] Linux Asp 4.4.30-mod-std-ipv6-64
 - Java Version: [e.g. Java 8] 8
 - BentoBox version: [e.g. 1.7.2.21] 
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
`:38:03 INFO]: Bentobox version: 1.0
[09:38:03 INFO]: Loaded Game Worlds:
[09:38:03 INFO]: island (island)
[09:38:03 INFO]: Loaded Add-Ons
[09:38:03 INFO]: BSkyBlock 1.0
[09:38:03 INFO]: Level 0.1.0-SNAPSHOT
[09:38:03 INFO]: BentoBox-Challenges 0.0.3-SNAPSHOT
[09:38:03 INFO]: WelcomeWarps 0.1.0-SNAPSHOT
`
 - Other plugins? [Do '/plugins' and copy/paste from the console]
https://sfy.cx/ss/u/e03d.png

**Additional context**
-

**Comment by Poslovitch** [comment] 2019-01-10 17:07
Duplicate of https://github.com/BentoBoxWorld/BentoBox/issues/457#issuecomment-453160961

**Closed by Poslovitch** 2019-01-10 17:07 UTC
