### ISSUE TITLE
Nether-End teleport

### ISSUE THREAD

**Issue by bckd00r** [BentoBoxWorld/BSkyBlock#384] opened 2020-11-26 23:34 UTC
Why can't we teleport to nether and end islands it's a mistake! needs to be added and edited.

/is reset (nether|end|normal)

/is tp (nether|end|normal)

portal should be able to be changed from custom config. (Nether and End)

Please take note of me. I have devoted a lot of time to this idea. </3

**Comment by tastybento** [comment] 2020-11-27 00:52
Duplicate of https://github.com/BentoBoxWorld/BentoBox/issues/1585

**Closed by tastybento** 2020-11-27 00:52 UTC
Labels: enhancement
